/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RPG_simulador;

public class App {

    public static void main(String[] args) {
        Personagem character = new Personagem("Null", 0, 0, 0.1, 0.1,0,0.1,0,0,0,0,0,0,0.1,0,0, "null", "null");
        Persona_criacao PerCri = new Persona_criacao();
        PerCri.Persona_criacao_menu(character);
        
    }
}
